# Generated by Django 3.2.9 on 2022-11-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(related_name='user_comments', to='movies.Comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='movies',
            field=models.ManyToManyField(related_name='user_like_movies', to='movies.Movie'),
        ),
    ]
