# Generated by Django 3.2.9 on 2022-11-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0002_auto_20221121_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genres',
            field=models.ManyToManyField(related_name='like_genres', to='movies.Genre'),
        ),
    ]
