# Generated by Django 3.2.9 on 2022-11-21 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='genres',
            new_name='like_genres',
        ),
    ]
